# Generated by Django 4.2.6 on 2023-11-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('experiencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boxeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('peso', models.CharField(choices=[('Pluma', 'Pluma'), ('Ligero', 'Ligero'), ('Semi-Pesado', 'Semi-Pesado'), ('Pesado', 'Pesado')], max_length=11)),
                ('edad', models.IntegerField()),
                ('peleas', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('edad', models.IntegerField()),
                ('experiencia', models.IntegerField()),
            ],
        ),
    ]
