# Generated by Django 4.2.6 on 2023-11-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxeador',
            name='edad',
            field=models.IntegerField(choices=[('5 a 12 años', '5 a 12 años'), ('13 a 17 años', '13 a 17 años'), ('+18', '+18')]),
        ),
    ]
