# Generated by Django 4.2.6 on 2023-11-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABE', '0002_alter_boxeador_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='experiencia',
            field=models.CharField(choices=[('Menor a 5 años', 'Menor a 5 años'), ('Mayor a 5 años', 'Mayor a 5 años'), ('Mayor a 10 años', 'Mayor a 10 años')], max_length=16),
        ),
        migrations.AlterField(
            model_name='boxeador',
            name='edad',
            field=models.CharField(choices=[('5 a 12 años', '5 a 12 años'), ('13 a 17 años', '13 a 17 años'), ('Mayor de edad', 'Mayor de edad')], max_length=16),
        ),
        migrations.AlterField(
            model_name='boxeador',
            name='peso',
            field=models.CharField(choices=[('Infantil', 'Infantil'), ('Adolescencia', 'Adolescencia'), ('Pluma', 'Pluma'), ('Ligero', 'Ligero'), ('Semi-Pesado', 'Semi-Pesado'), ('Pesado', 'Pesado')], max_length=16),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='experiencia',
            field=models.CharField(choices=[('Menor a 5 años', 'Menor a 5 años'), ('Mayor a 5 años', 'Mayor a 5 años'), ('Mayor a 10 años', 'Mayor a 10 años')], max_length=16),
        ),
    ]
